# Generated by Django 5.1.6 on 2025-06-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_innovation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalinnovation',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
